### ISSUE TITLE
beta31 magisk版在/data/abd/modules/ZJLPreventNetworkTrafficDeductionScript/ZJL2.0_magisk下扔会产生文件

### ISSUE THREAD

**Issue by schalkiii** [EternalPain/ZJL#18]
beta31 change log描述脚本目录更改到/data/防跳/ZJL2.0_magisk但是在/data/abd/modules/ZJLPreventNetworkTrafficDeductionScript/ZJL2.0_magisk下扔会产生文件， 且二者不是软链接。

**Comment by 365360171** [comment]
/data/abd/modules 这个路径是magisk安装模块后默认的模块路径。

**Comment by EternalPain** [comment]
去看 Magisk 的Github
