### ISSUE TITLE
安卓12 接入点读取信息

### ISSUE THREAD

**Issue by JamesLiu0802** [EternalPain/ZJL#36]
在安卓12上使用时在接入点会有额外信息读取，而且开启wifi时打开会提示热点已经连接。
![fce514f67ba2af045a447cb323730ab](https://user-images.githubusercontent.com/86506347/147443106-b609cb0e-0d71-43d2-ae49-8c0547b261e8.jpg)

**Comment by liwenjie119** [comment]
修改ZJL文件869:80，把，改为}，apn显示就正常了。其他不知道怎么修

**Comment by JamesLiu0802** [comment]
可以了，谢谢
