### ISSUE TITLE
28版本

### ISSUE THREAD

**Issue by yuxuxin233** [EternalPain/ZJL#8]
怎么不放行UDP也能游戏了…

**Comment by EternalPain** [comment]
你怕是用了cns代理吧 或者放行了游戏uid

**Comment by yuxuxin233** [comment]
没有啊，在安卓11不放行UDP都可以直接玩，然而降级到安卓9王者需要放行UDP了…------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;EternalPain&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月7日(星期天) 中午1:23
收件人:&nbsp;&quot;EternalPain/ZJL&quot;<ZJL@noreply.github.com&gt;;
抄送:&nbsp;&quot;yuxuxin233&quot;<x2874836915@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EternalPain/ZJL] 28版本 (#8)

**Comment by EternalPain** [comment]
？不可能的 只能代理或者放行 你加我QQ 发配置截图

**Comment by yuxuxin233** [comment]
真的不骗你安卓11和平精英，王者荣耀直接不用放行UDP就可以直接玩但是还是会扣正常流量！安卓9和平精英不用放行王者荣耀要放行…------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;EternalPain&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月7日(星期天) 晚上11:31
收件人:&nbsp;&quot;EternalPain/ZJL&quot;<ZJL@noreply.github.com&gt;;
抄送:&nbsp;&quot;yuxuxin233&quot;<x2874836915@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [EternalPain/ZJL] 28版本 (#8)

**Comment by EternalPain** [comment]
。。。。你扣了正常流量就是放行了

**Comment by EternalPain** [comment]
我写的那些我还不知道吗
